language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1
  - nightly

install:
  - composer install

before_script:
  - composer update --lock

script:
  - ./vendor/bin/php-cs-fixer --config=./.php-cs-fixer.dist.php fix --dry-run --diff --allow-risky=yes
  - ./vendor/bin/phpstan
  - php vendor/bin/phpunit -d xdebug.mode=coverage vendor/bin/phpunit -vv --testsuite unit,functional,integration,e2e
