version: 2

executors:
  php81-cli:
    docker:
      - image: maszdockerid/php8.1-ci-cli-alpine:latest
    working_directory: /app

jobs:

  build:
    executor: php81-cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - persist_to_workspace:
          root: /app
          paths:
            - *

  analyse:
    executor: php81-cli
    steps:
      - attach_workspace:
          at: /app
      - run: ./vendor/bin/php-cs-fixer --config=./.php-cs-fixer.dist.php fix --dry-run --diff --allow-risky=yes
      - run: ./vendor/bin/phpstan

  test:
    executor: php81-cli
    steps:
      - attach_workspace:
          at: /app
      - run: ./vendor/bin/phpunit -vv --testsuite unit,functional,integration,e2e

workflows:
  version: 2
  all:
    jobs:
      - build
      - analyse:
          requires:
            - build
      - test:
          requires:
            - build
